config/routes.rb
RozkladCzestPl::Application.routes.draw do

  get "schedules", :controller => 'schedules', :action => 'index', :as => 'schedules_index'
  get "stations", :controller => 'schedules', :action => 'stations', :as => 'schedules_stations'
  get "stations/:id", :controller => 'schedules', :action => 'station', :as => 'schedules_station'
  get "lines", :controller => 'schedules', :action => 'lines', :as => 'schedules_lines'
  get "lines/:number", :controller => 'schedules', :action => 'line', :as => 'schedules_line'
  get "line_road/:id", :controller => 'schedules', :action => 'line_road', :as => 'schedules_line_road'
  get "line_road_map/:id", :controller => 'schedules', :action => 'line_road_map', :as => 'schedules_line_road_map'
  get "schedules/schedule/:line_id/:station_id", :controller => 'schedules', :action => 'schedule', :as => 'schedules_schedule'

  get "log_out" => "sessions#destroy", :as => 'log_out'
  resources :users do
    resources :favourites
  end
  resources :sessions

  root :to => 'pages#index'
  post 'pages/get_location'
  get 'pages/static_map'
  get 'pages/info'
  get 'search_schedule/new_search'
  get 'search_schedule/autocomplete_station_name'
  get 'search_schedule/search'
  get 'search_schedule/map'

end

app/models/favourite.rb
# coding: utf-8
class Favourite < ActiveRecord::Base
  
  belongs_to :user
  before_validation :upcase_stations
  validate :validate_station_from_exist,
           :validate_station_to_exist,
           :validate_line_exist

  scope :on_start_page, :conditions => { :on_start_page => true }

  private

    def upcase_stations
      self.station_from = station_from.upcase
      self.station_to = station_to.upcase
    end

    def validate_station_from_exist
      errors.add :station_from, 'Przystanek odjazdowy nie istnieje.' unless station_from_object
    end

    def validate_station_to_exist
      errors.add :station_to, 'Przystanek docelowy nie istnieje.' unless station_to_object
    end

    def validate_line_exist
      if station_from_object and station_to_object
        errors.add :station_from, 'Brak połączeń.' unless Line.find_first_by_stations(station_from_object.id, station_to_object.id)
      end
    end

    def station_from_object
      @station_from_object ||= Station.find_by_name(station_from)
    end

    def station_to_object
      @station_to_object ||= Station.find_by_name(station_to)
    end

end

app/controllers/favourites_controller.rb
# coding: utf-8
class FavouritesController < ApplicationController

  before_filter do
    logged_in? && authorize?
  end

  def logged_in?
    defined?(session[:user_id])
  end

  def authorize?
    redirect_to root_path unless params[:user_id].to_i == session[:user_id]
  end

  def index
    @user = User.find(params[:user_id])
    @favourites = @user.favourites
  end

  def show
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.new
  end

  def create
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.build(params[:favourite])
    if @favourite.save
      redirect_to user_favourites_path(@user)
    else
      flash[:errors] = @favourite.errors
      render :template => pages_info_path
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
    if @favourite.update_attributes(params[:favourite])
      redirect_to user_favourites_path(@user)
    else
      flash[:errors] = @favourite.errors
      render :template => pages_info_path
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
    @favourite.destroy
    redirect_to user_favourites_path(@user)
  end

end

app/views/favourites/_form.html.haml
%h2 Ulubione
= form_for [@user, @favourite] do |f|

  = f.label :name, 'Nazwa', :class => 'grid_2 alpha prefix_1' 
  = f.text_field :name, :class => 'grid_2 omega'

  .clear.vertical_spacer

  = f.label :station_from, 'Przystanek odjazdowy', :class => 'grid_2 alpha prefix_1' 
  = f.autocomplete_field :station_from,
                 search_schedule_autocomplete_station_name_path,
                 :class => 'grid_2 omega'

  .clear.vertical_spacer

  = f.label :station_to, 'Przystanek docelowy', :class => 'grid_2 alpha prefix_1'
  = f.autocomplete_field :station_to,
                 search_schedule_autocomplete_station_name_path,
                 :class => 'grid_2 omega'

  .clear.vertical_spacer

  %input{:name => 'favourite[on_start_page]', :type => 'hidden', :value => '0'}
  = f.label :on_start_page, 'Pokaż na stronie startowej', :class => 'grid_2 alpha prefix_1'
  = check_box_tag 'favourite[on_start_page]', '1', @favourite.on_start_page, :class => 'grid_2 omega'

  .clear.vertical_spacer

  .grid_2.alpha.prefix_2
    = f.submit 'Zapisz'

app/views/favourites/edit.html.haml
.prefix_3
  .grid_6.box
    = render 'form'
    .grid_2.omega
      = button_to 'Usuń', "/users/#{@user.id}/favourites/#{@favourite.id}", :method => 'delete'

app/views/favourites/index.html.haml
.prefix_3
  .grid_6.box
    %h2 Ulubione
    %ul{'data-role' => 'listview'}
      - unless @favourites.empty?
        - @favourites.each do |favourite|
          %li
            = link_to favourite.name,
              search_schedule_search_path(:station_from => favourite.station_from,
                                          :station_to => favourite.station_to,
                                          :from => 'station',
                                          :to => 'station'), :class => 'grid_2 alpha prefix_1'
            = link_to 'Edytuj', edit_user_favourite_path(current_user.id,favourite.id), 'data-icon' => 'gear', :class => 'grid_2'
          .clear
      - else
        %li W tej chwili nie masz żadnych ulubionych.

    .vertical_spacer
    .mobile_spacer

    .grid_2.alpha.prefix_4
      = button_to 'Dodaj', new_user_favourite_path, :method => :get, 'data-icon' => 'plus'

app/views/favourites/new.html.haml
.prefix_3
  .grid_6.box
    = render 'form'