config/routes.rb
RozkladCzestPl::Application.routes.draw do

  get "schedules", :controller => 'schedules', :action => 'index', :as => 'schedules_index'
  get "stations", :controller => 'schedules', :action => 'stations', :as => 'schedules_stations'
  get "stations/:id", :controller => 'schedules', :action => 'station', :as => 'schedules_station'
  get "lines", :controller => 'schedules', :action => 'lines', :as => 'schedules_lines'
  get "lines/:number", :controller => 'schedules', :action => 'line', :as => 'schedules_line'
  get "line_road/:id", :controller => 'schedules', :action => 'line_road', :as => 'schedules_line_road'
  get "line_road_map/:id", :controller => 'schedules', :action => 'line_road_map', :as => 'schedules_line_road_map'
  get "schedules/schedule/:line_id/:station_id", :controller => 'schedules', :action => 'schedule', :as => 'schedules_schedule'

  get "log_out" => "sessions#destroy", :as => 'log_out'
  resources :users do
    resources :favourites
  end
  resources :sessions

  root :to => 'pages#index'
  post 'pages/get_location'
  get 'pages/static_map'
  get 'pages/info'
  get 'search_schedule/new_search'
  get 'search_schedule/autocomplete_station_name'
  get 'search_schedule/search'
  get 'search_schedule/map'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  GET_LIMIT = 10
  TODAY_LIMIT = GET_LIMIT

  belongs_to :line
  belongs_to :station

  def self.today(lines_id, station_from_id)
    find(:all,
      :conditions => [
        "line_id IN (?)
          AND station_id = ?
          AND arrival_at > ?
          AND ((sunday = 't' AND saturday = 't' AND work = 't' AND holiday = 't')
          OR (sunday = ? AND saturday = ? AND work = ? AND holiday = ?)
          OR (sunday = ? AND saturday = ? AND work = 'f' AND holiday = 'f'))",
        lines_id,
        station_from_id,
        Time.now,
        Time.now.at_beginning_of_day.wday == 0,
        Time.now.at_beginning_of_day.wday == 6,
        (!night_weekend? && !holiday?),
        holiday?,
        night_weekend?,
        night_weekend?
      ],
      :order => 'arrival_at',
      :limit => TODAY_LIMIT
    )
  end

  def self.tomorrow(lines_id, station_from_id, limit)
    find(:all,
      :conditions => [
        "line_id IN (?)
          AND station_id = ?
          AND arrival_at > ?
          AND ((sunday = 't' AND saturday = 't' AND work = 't' AND holiday = 't')
          OR (sunday = ? AND saturday = ? AND work = ? AND holiday = ?)
          OR (sunday = ? AND saturday = ? AND work = 'f' AND holiday = 'f'))",
        lines_id,
        station_from_id,
        Time.now.tomorrow.at_beginning_of_day,
        Time.now.tomorrow.at_beginning_of_day.wday == 0,
        Time.now.tomorrow.at_beginning_of_day.wday == 6,
        (!tomorrow_night_weekend? && !tomorrow_holiday?),
        tomorrow_holiday?,
        tomorrow_night_weekend?,
        tomorrow_night_weekend?
    ],
      :order => 'arrival_at',
      :limit => limit
    )
  end

  def self.get(station_from_id, station_to_id)
    lines_id = Line.ids_by_stations(station_from_id, station_to_id)
    today_schedules = Schedule.today(lines_id, station_from_id)
    left = GET_LIMIT - today_schedules.count
    if left > 0
      tomorrow_schedules = Schedule.tomorrow(lines_id, station_from_id, left)
      schedules = today_schedules + tomorrow_schedules
    else
      schedules = today_schedules
    end
    { :schedules => schedules, :station_to => Station.find(station_to_id) }
  end

  def self.get_by_near_stations_and_station_to(within, location, station_to_id)
    schedules = []
    Station.within(Station.to_f(within), :origin => location).order('distance asc').each { |station| schedules << get(station.id, station_to_id) if Line.find_first_by_stations(station.id, station_to_id) }
    schedules
  end

  def self.get_by_station_from_and_location(station_from_id, location)
    schedules = []
    Station.within(0.5, :origin => Schedule.location_to_latlng(location)).order('distance asc').each do |station|
      schedules << Schedule.get(station_from_id, station.id) if Line.find_first_by_stations(station_from_id, station.id)
    end
    schedules
  end

  def self.get_by_near_stations_and_location(within, my_location, location)
    schedules = []
    stations_near = Station.within(Station.to_f(within), :origin => my_location).order('distance asc')
    stations_to = Station.within(0.5, :origin => Schedule.location_to_latlng(location)).order('distance asc')
    stations_near.each do |station_from|
      stations_to.each do |station_to|
        schedules << Schedule.get(station_from.id, station_to.id) if Line.find_first_by_stations(station_from.id, station_to.id)
      end
    end
    schedules
  end

  def self.location_to_latlng(location)
    location = location.to_ascii
    if location =~ /,/
      location_geocoded = Geokit::Geocoders::GoogleGeocoder.geocode(location)
    else
      location = "Czestochowa, " + location
      location_geocoded = Geokit::Geocoders::GoogleGeocoder.geocode(location)
    end
    [location_geocoded.lat, location_geocoded.lng]
  end
      

  def self.paginate_by_hour(line_id, station_id, time_type)
    paginated_schedules = []
    _schedules = []
    schedules = Schedule.where(:line_id => line_id, :station_id => station_id, time_type => true).select(:arrival_at).collect(&:arrival_at)
    unless schedules.empty?
      last_hour = schedules.first.hour
      schedules.each do |schedule|
        if schedule.hour != last_hour
          last_hour = schedule.hour
          paginated_schedules << _schedules
          _schedules = []
        end
        _schedules << schedule
      end
      paginated_schedules << _schedules
    end
    paginated_schedules
  end

  def self.holiday?
    holiday_months = Time.now.month == 7 || Time.now.month == 8
    working_days = Time.now.at_beginning_of_day.wday != 6 && Time.now.at_beginning_of_day.wday != 0
    @holiday ||= holiday_months && working_days
  end

  def self.tomorrow_holiday?
    holiday_months = Time.now.tomorrow.month == 7 || Time.now.tomorrow.month == 8
    working_days = Time.now.tomorrow.at_beginning_of_day.wday != 6 && Time.now.tomorrow.at_beginning_of_day.wday != 0
    @tomorrow_holiday ||= holiday_months && working_days
  end

  def self.night_weekend?
    @night_weekend ||= Time.now.at_beginning_of_day.wday == 0 || Time.now.at_beginning_of_day.wday == 6
  end

  def self.tomorrow_night_weekend?
    @tomorrow_night_weekend ||= Time.now.tomorrow.at_beginning_of_day.wday == 0 || Time.now.tomorrow.at_beginning_of_day.wday == 6
  end

end

app/controllers/schedules_controller.rb
#coding: utf-8
class SchedulesController < ApplicationController

  def index
  end

  def stations
    @stations_ordered = Station.paginate_by_letter
  end

  def station
    @station = Station.find(params[:id])
    @lines = @station.lines
  end

  def lines
    @lines = Line.get_numbers
  end

  def line
    @number = params[:number]
    @lines = Line.where(:number => @number)
  end

  def line_road 
    @line = Line.find(params[:id])
    @stations = @line.stations
  end

  def line_road_map
    @line_map_url = Line.find(params[:id]).map_url
  end

  def schedule
    @schedules_work = Schedule.paginate_by_hour(params[:line_id], params[:station_id], :work)
    @schedules_sunday = Schedule.paginate_by_hour(params[:line_id], params[:station_id], :sunday)
    @schedules_saturday = Schedule.paginate_by_hour(params[:line_id], params[:station_id], :saturday)
    @schedules_holiday = Schedule.paginate_by_hour(params[:line_id], params[:station_id], :holiday)
    if @schedules_work.empty?
      flash[:error] = 'Brak tablicy rozkładów dla tego przystanku.'
      render :template => pages_info_path
    end
  end

end

app/views/schedules/index.html.haml
.prefix_3
  %ul.grid_6.box{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} Rozkłady
    %li= link_to "Dla przystanku", schedules_stations_path
    %li= link_to "Dla linii", schedules_lines_path
    %li= link_to "Mapa przystanków", pages_static_map_path

app/views/schedules/line.html.haml
.prefix_3
  %ul.grid_6.box{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'}= @number
    - @lines.each do |line|
      %li= link_to "#{line.number} - kierunek: #{line.direction}", schedules_line_road_path(line)

app/views/schedules/line_road.html.haml
.prefix_3
  %ul.grid_6.box{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'}= "#{@line.number} - kierunek: #{@line.direction}"
    - @stations.each do |station|
      %li= link_to station.name, schedules_schedule_path(:line_id => @line.id, :station_id => station.id)

app/views/schedules/line_road_map.html.haml
%iframe{:frameborder => "0", :height => "350", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => @line_map_url, :width => "425"}

app/views/schedules/lines.html.haml
.prefix_4
  %ul.grid_4.box{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} LINIE
    - @lines.each do |line|
      %li
        %b= link_to line, schedules_line_path(:number => line)

app/views/schedules/schedule.html.haml
- unless @schedules_work.nil?
  %ul.grid_6.box.cell{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} Robocze
    - @schedules_work.each do |hour|
      %li
        %b.hour= hour.first.hour
        - hour.each do |minute|
          = minute.min
    .mobile_spacer

- unless @schedules_saturday.nil?
  %ul.grid_6.box.cell{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} Soboty
    - @schedules_saturday.each do |hour|
      %li
        %b.hour= hour.first.hour
        - hour.each do |minute|
          = minute.min
    .mobile_spacer

.clear

- unless @schedules_sunday.nil?
  %ul.grid_6.box.cell{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} Niedziele i święta
    - @schedules_sunday.each do |hour|
      %li
        %b.hour= hour.first.hour
        - hour.each do |minute|
          = minute.min
    .mobile_spacer

- unless @schedules_holiday.nil?
  %ul.grid_6.box.cell{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'} Wakacyjne
    - @schedules_holiday.each do |hour|
      %li
        %b.hour= hour.first.hour
        - hour.each do |minute|
          = minute.min

app/views/schedules/station.html.haml
.prefix_3
  %ul.grid_6.box{'data-role' => 'listview'}
    %li.title{'data-role' => 'list-divider'}= @station.name
    - @lines.each do |line|
      %li= link_to "#{line.number} - kierunek: #{line.direction}", schedules_line_road_path(line), :class => 'grid_4 alpha'

app/views/schedules/stations.html.haml
.prefix_3
  - @stations_ordered.each do |stations|
    %ul.grid_6.box{'data-role' => 'listview'}
      %li.title{'data-role' => 'list-divider'}= stations.first.name.first
      - stations.each do |station|
        %li= link_to station.name, schedules_station_path(station), :class => 'grid_4 alpha'

      .mobile_spacer