config/routes.rb
RozkladCzestPl::Application.routes.draw do

  get "schedules", :controller => 'schedules', :action => 'index', :as => 'schedules_index'
  get "stations", :controller => 'schedules', :action => 'stations', :as => 'schedules_stations'
  get "stations/:id", :controller => 'schedules', :action => 'station', :as => 'schedules_station'
  get "lines", :controller => 'schedules', :action => 'lines', :as => 'schedules_lines'
  get "lines/:number", :controller => 'schedules', :action => 'line', :as => 'schedules_line'
  get "line_road/:id", :controller => 'schedules', :action => 'line_road', :as => 'schedules_line_road'
  get "line_road_map/:id", :controller => 'schedules', :action => 'line_road_map', :as => 'schedules_line_road_map'
  get "schedules/schedule/:line_id/:station_id", :controller => 'schedules', :action => 'schedule', :as => 'schedules_schedule'

  get "log_out" => "sessions#destroy", :as => 'log_out'
  resources :users do
    resources :favourites
  end
  resources :sessions

  root :to => 'pages#index'
  post 'pages/get_location'
  get 'pages/static_map'
  get 'pages/info'
  get 'search_schedule/new_search'
  get 'search_schedule/autocomplete_station_name'
  get 'search_schedule/search'
  get 'search_schedule/map'

end

app/controllers/search_schedule_controller.rb
# coding: utf-8
class SearchScheduleController < ApplicationController

  autocomplete :station, :name, :full => true

  def search
    if params[:to] == 'station'
      if @station_to = Station.find_by_name(params[:station_to].upcase)
        if params[:from] == 'station'
          if @station_from = Station.find_by_name(params[:station_from].upcase)
            if Line.find_first_by_stations(@station_from.id, @station_to.id)
              @schedules = [Schedule.get(@station_from.id, @station_to.id)]
            else
              flash[:error] = 'Brak połączeń.'
              render :template => pages_info_path
            end
          else
            flash[:error] = 'Przystanek odjazdowy nie istnieje.'
            render :template => pages_info_path
          end
        else
          if my_location = [session[:lat], session[:lng]]
            @schedules = Schedule.get_by_near_stations_and_station_to(params[:within], my_location, @station_to.id)
            if @schedules.empty?
              flash[:error] = 'Brak połączeń.'
              render :template => pages_info_path
            end
          else
            flash[:error] = 'Nie udostępniono położenia.'
            render :template => pages_info_path
          end
        end
      else
        flash[:error] = 'Przystanek docelowy nie istnieje.'
        render :template => pages_info_path
      end
    else
      if params[:from] == 'station'
        if @station_from = Station.find_by_name(params[:station_from].upcase)
          @schedules = Schedule.get_by_station_from_and_location(@station_from.id, params[:location_to])
          if @schedules.empty?
            flash[:error] = 'Brak połączeń.'
            render :template => pages_info_path
          end
        else
          flash[:error] = 'Przystanek odjazdowy nie istnieje.'
          render :template => pages_info_path
        end
      else
        if my_location = [session[:lat], session[:lng]]
          @schedules = Schedule.get_by_near_stations_and_location(params[:within], my_location, params[:location_to])
          if @schedules.empty?
            flash[:error] = 'Brak połączeń.'
            render :template => pages_info_path
          end
        else
          flash[:error] = 'Nie udostępniono położenia.'
          render :template => pages_info_path
        end
      end
    end
  end

  def map
    @lat = session[:lat]
    @lng = session[:lng]
    @station_from = Station.find(params[:station_from])
    @station_to = Station.find(params[:station_to])
    unless @lat
      flash[:error] = 'Jeżeli chcesz korzystać z funkcji mapy, musisz najpierw udostępnić swoje położenie.'
      render :template => pages_info_path
    end
  end

end

app/views/search_schedule/map.html.haml
.grid_12{:id => "map"}

:javascript
  function getMap() {
    var latlng = new google.maps.LatLng(#{@lat},#{@lng});
    var myOptions = {
      zoom: 13,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById('map'),myOptions);

    var myLatLng = new google.maps.LatLng(#{@lat},#{@lng});
    var my = new google.maps.Marker({
      position: myLatLng,
      map: map, 
      icon: 'http://www.google.com/intl/en_ALL/mapfiles/markerT.png',
      title: 'Ty'
    });

    var fromLatLng = new google.maps.LatLng(#{@station_from.lat},#{@station_from.lng});
    var from = new google.maps.Marker({
      position: fromLatLng,
      map: map,
      icon: 'http://www.google.com/intl/en_ALL/mapfiles/markerZ.png',
      title: 'Z'
    });

    var toLatLng = new google.maps.LatLng(#{@station_to.lat},#{@station_to.lng});
    var to = new google.maps.Marker({
      position: toLatLng,
      map: map,
      icon: 'http://www.google.com/intl/en_ALL/mapfiles/markerD.png',
      title: 'Do'
    });
  }

app/views/search_schedule/new_search.html.haml
.prefix_3
  .grid_6.box
    %h2 Szukaj połączenia
    = form_tag search_schedule_search_path, :method => :get do
      %div.grid_6.alpha{"data-role" => "fieldcontain"}
        %fieldset{"data-role" => "controlgroup"}
          %legend{:class => 'grid_2 alpha prefix_1'} Odjazd
          .grid_2.omega
            = radio_button_tag :from, :station, true
            = label_tag :from_station, 'Z przystanku'
          .grid_3.alpha.prefix_3
            = radio_button_tag :from, :location, false
            = label_tag :from_location, 'Z mojego położenia'
        .input_toggle
          #station_from_container
            = label_tag :station_from, 'Przystanek odjazdowy', :class => 'grid_3 alpha'
            = autocomplete_field_tag :station_from, '', search_schedule_autocomplete_station_name_path, :class => 'grid_2 omega'
          #within_container
            = label_tag :within, 'W promieniu (w metrach)', :class => 'grid_3 alpha'
            - if session[:mobile] 
              = range_field_tag :within, 500, :min => 100, :max => 2000, :step => 100
            - else 
              = text_field_tag :within, '500', :class => 'grid_2 omega'

      .vertical_spacer

      %div.grid_6.alpha{"data-role" => "fieldcontain"}
        %fieldset{"data-role" => "controlgroup"}
          %legend{:class => 'grid_2 alpha prefix_1'} Przyjazd
          .grid_2.omega
            = radio_button_tag :to, :station, true
            = label_tag :to_station, 'Do przystanku'
          .grid_3.alpha.prefix_3
            = radio_button_tag :to, :location, false
            = label_tag :to_location, 'Na adres'
        .input_toggle
          #station_to_container
            = label_tag :station_to, 'Przystanek docelowy', :class => 'grid_2 alpha prefix_1'
            = autocomplete_field_tag :station_to, '', search_schedule_autocomplete_station_name_path, :class => 'grid_2 omega'
          #location_to_container
            = label_tag :location_to, 'Adres docelowy', :class => 'grid_2 alpha prefix_1'
            = text_field_tag :location_to, '', :class => 'grid_2 omega'

      .vertical_spacer

      %div{:class => 'grid_2 alpha prefix_2'}= button_to_function 'Odśwież położenie', 'getLocation();'

      .grid_2.omega
        = submit_tag 'Szukaj', 'data-icon' => 'forward'

:javascript
  $("input[name='from']").bind("change", function() {
    $('#within_container').toggle('slow');
    $('#station_from_container').toggle('slow');
  });

  $("input[name='to']").bind("change", function() {
    $('#location_to_container').toggle('slow');
    $('#station_to_container').toggle('slow');
  });

app/views/search_schedule/search.html.haml
- @schedules.each do |station_schedules|
  %ul.grid_6.box{'data-role' => 'listview', :style => 'min-height: 273px;'}
    %li.title{'data-role' => 'list-divider'}
      %div= "Z: #{station_schedules[:schedules].first.station.name}"
      %div= "Kierunek: #{station_schedules[:schedules].first.line.direction}"
      %div= "Do: #{station_schedules[:station_to].name}"
    - station_schedules[:schedules].each do |schedule|
      %li= link_to "#{schedule.line.number} o #{schedule.arrival_at.strftime("%H:%M")}",
        search_schedule_map_path(:station_from => schedule.station.id, :station_to => station_schedules[:station_to].id), :rel => 'external'
    - if current_user && current_user.favourites.where(:station_from => station_schedules[:schedules].first.station.name, :station_to => station_schedules[:station_to].name).empty?
      %li
        %b= link_to 'Dodaj do ulubionych',
        { :controller => 'favourites',
          :action => 'create',
          :user_id => current_user.id,
          :favourite => { :name => "#{station_schedules[:schedules].first.station.name} -> #{station_schedules[:station_to].name}",
          :station_from => station_schedules[:schedules].first.station.name,
          :station_to => station_schedules[:station_to].name } },:method => :post
    .mobile_spacer