config/routes.rb
RozkladCzestPl::Application.routes.draw do

  get "schedules", :controller => 'schedules', :action => 'index', :as => 'schedules_index'
  get "stations", :controller => 'schedules', :action => 'stations', :as => 'schedules_stations'
  get "stations/:id", :controller => 'schedules', :action => 'station', :as => 'schedules_station'
  get "lines", :controller => 'schedules', :action => 'lines', :as => 'schedules_lines'
  get "lines/:number", :controller => 'schedules', :action => 'line', :as => 'schedules_line'
  get "line_road/:id", :controller => 'schedules', :action => 'line_road', :as => 'schedules_line_road'
  get "line_road_map/:id", :controller => 'schedules', :action => 'line_road_map', :as => 'schedules_line_road_map'
  get "schedules/schedule/:line_id/:station_id", :controller => 'schedules', :action => 'schedule', :as => 'schedules_schedule'

  get "log_out" => "sessions#destroy", :as => 'log_out'
  resources :users do
    resources :favourites
  end
  resources :sessions

  root :to => 'pages#index'
  post 'pages/get_location'
  get 'pages/static_map'
  get 'pages/info'
  get 'search_schedule/new_search'
  get 'search_schedule/autocomplete_station_name'
  get 'search_schedule/search'
  get 'search_schedule/map'

end

app/views/layouts/_content.html.haml
%div{'data-role' => 'content', :style => (current_action?('map') || current_action?('static_map') and session[:mobile]) ? 'width:100%; height:100%; padding:0;' : nil}
  = yield
.push

app/views/layouts/_footer.html.haml
.container_12{'data-role' => 'footer'}
  .grid_2.alpha
    %iframe{:allowTransparency => "true", :frameborder => "0", :scrolling => "no", :src => "http://www.facebook.com/plugins/like.php?locale=pl_PL&app_id=227536533961515&href=http%3A%2F%2Ffacebook.com%2Frozkladczestpl&send=false&layout=button_count&width=450&show_faces=false&action=like&colorscheme=light&font=arial&height=21", :style => "border:none; overflow:hidden; width:450px; height:21px;"}
  .grid_4
    Copyright©2011 
    %span.normal_nav= link_to 'DoubleDrones.com', 'http://doubledrones.com'
  .grid_4
    Design and Coding by 
    %span.normal_nav= link_to 'DoubleDrones.com', 'http://doubledrones.com'
  .grid_2.omega
    Wejdź przez telefon

app/views/layouts/_header.html.haml
%div{'data-role' => 'header'}
  - unless session[:mobile]
    #logo
      .grid_6.prefix_4{:style => 'margin-top: 4em;'}
        %h1{:style => 'margin-bottom:0;'} Rozklad.czest.pl
        #desc Jedyny serwis wyszukujący połączenia komunikacji miejskiej w Częstochowie.
  %div{'data-role' => 'navbar'}
    %ul
      %li.normal_nav= link_to 'Index', root_path, :rel => 'external'
      %li.search
        %b= link_to 'Szukaj', search_schedule_new_search_path, :rel => 'external'
      - if current_user
        %li.normal_nav= link_to 'Ulubione', user_favourites_path(current_user.id), :rel => 'external'
      %li.normal_nav= link_to 'Rozkłady', schedules_index_path, :rel => 'external'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    :javascript
      window.location="http://rozklad.czest.pl";
  %body

app/views/layouts/pages.html.haml
<!DOCTYPE html>
%html
	%head
		=stylesheet_link_tag 'ext-touch'
		=javascript_include_tag 'autocomplete_data'
		=javascript_include_tag 'ext-touch-debug'
		=javascript_include_tag 'index'
	%body